### ISSUE TITLE
No mac (or windows/source) packages means the installation fails.

### ISSUE THREAD

**Issue by alexlatchford** [mindsdb/dfsql#20]
Hello! I'm getting this error when I try to install via `poetry add "modin[sql]"` on my Macbook (outside of a Docker image):

```
$ poetry add "modin[sql]"
Using version ^0.10.1 for modin

Updating dependencies
Resolving dependencies... (0.6s)
Resolving dependencies... (0.3s)

Package operations: 2 installs, 0 updates, 0 removals

  • Installing dfsql (0.3.1): Failed

  RuntimeError

  Unable to find installation candidates for dfsql (0.3.1)

  at ~/.poetry/lib/poetry/installation/chooser.py:72 in choose_for
       68│
       69│             links.append(link)
       70│
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│
       76│         # Get the best link


Failed to add packages, reverting the pyproject.toml file to its original content.
```

Doing a bit of digging looks like [this change](https://github.com/mindsdb/dfsql/pull/10) was made to just publish Linux wheels only, not able to understand the context behind that change given the lack of a description. I'm happy to throw together a quick Dockerfile to get my project to compile so I can try this out but figured I'd create an issue as likely others in the near future will hit this same problem!

**Comment by btseytlin** [comment]
@alexlatchford thank you for this issue, we will bring windows and mac support back shortly

**Comment by btseytlin** [comment]
Brought back source package uploading in this PR: https://github.com/mindsdb/dfsql/pull/19

**Comment by alexlatchford** [comment]
Sweet thanks, can confirm this is working with `v0.4.4`
